export const boardConstants = {
	GET_BOARD_LIST: 'GET_BOARD_LIST',
	GET_BOARD_LIST_SUCCESS: 'GET_BOARD_LIST_SUCCESS',
	GET_BOARD_LIST_ERROR: 'GET_BOARD_LIST_ERROR',
	GET_BOARD_DETAIL: 'GET_BOARD_DETAIL',
	GET_BOARD_DETAIL_SUCCESS: 'GET_BOARD_DETAIL_SUCCESS',
	GET_BOARD_DETAIL_ERROR: 'GET_BOARD_DETAIL_ERROR',
}
