export const constants = {
	SHOW_ALERT: 'SHOW_ALERT',
	CLOSE_ALERT: 'CLOSE_ALERT',
	SHOW_CONFIRM: 'SHOW_CONFIRM',
	CLOSE_CONFIRM: 'CLOSE_CONFIRM',
	ADD_USER: 'ADD_USER',
	SET_INIT_USER: 'SET_INIT_USER',
	SET_LANG: 'SET_LANG',
}
